package org.sonatype.nexus.test.launcher;

import static org.sonatype.nexus.test.utils.PortUtil.getRandomPort;

import java.io.File;
import java.io.FileOutputStream;
import java.util.ArrayList;
import java.util.List;
import java.util.Properties;
import java.util.Set;

import org.apache.commons.beanutils.BeanUtils;
import org.codehaus.plexus.PlexusContainer;
import org.codehaus.plexus.component.repository.ComponentDescriptor;
import org.codehaus.plexus.component.repository.ComponentRequirement;
import org.codehaus.plexus.configuration.PlexusConfiguration;
import org.codehaus.plexus.configuration.xml.XmlPlexusConfiguration;
import org.codehaus.plexus.util.cli.StreamConsumer;
import org.sonatype.appbooter.DefaultForkedAppBooter;
import org.sonatype.appbooter.ForkedAppBooter;
import org.sonatype.appbooter.ctl.ControllerClient;
import org.sonatype.nexus.rest.model.StatusResource;
import org.sonatype.nexus.test.utils.NexusIllegalStateException;
import org.sonatype.nexus.test.utils.NexusStatusUtil;
import org.sonatype.nexus.test.utils.TestProperties;

public class ForkedNexusInstancesFactory
    implements INexusInstancesFactory
{

    private List<NexusContext> contexts;

    private PlexusContainer container;

    public ForkedNexusInstancesFactory( PlexusContainer container )
    {
        this.contexts = new ArrayList<NexusContext>();
        this.container = container;
    }

    private void addChild( PlexusConfiguration cfg, String name, String value )
    {
        PlexusConfiguration child = cfg.getChild( name );
        if ( child != null )
        {
            child.setValue( value );
        }
        else
        {
            cfg.addChild( name, value );
        }
    }

    private void sleep( int i )
    {
        try
        {
            Thread.sleep( i );
        }
        catch ( InterruptedException e )
        {
            // ok
        }
    }

    public NexusContext createInstance()
        throws Exception
    {
        Integer nexusPort = getRandomPort();
        String nexusWorkDir = TestProperties.getPath( "nexus.work.dir" ) + nexusPort;
        return createInstance( nexusPort, nexusWorkDir );
    }

    /*
     * (non-Javadoc)
     * @see org.sonatype.nexus.test.launcher.INexusInstancesFactory#createInstance()
     */
    public NexusContext createInstance( Integer nexusPort, File nexusWorkDir )
        throws Exception
    {
        return createInstance( nexusPort, nexusWorkDir.getAbsolutePath() );
    }

    private NexusContext createInstance( Integer nexusPort, String nexusWorkDir )
        throws Exception
    {
        Integer controllerPort = getRandomPort();
        String nexusBaseDir = TestProperties.getPath( "nexus.base.dir" );
        String nexusApp = nexusBaseDir + "/runtime/apps/nexus";

        Properties plexusProps = new Properties();
        plexusProps.setProperty( "application-port", nexusPort.toString() );
        plexusProps.setProperty( "application-host", "0.0.0.0" );
        plexusProps.setProperty( "runtime", nexusBaseDir + "/runtime" );
        plexusProps.setProperty( "runtime-tmp", nexusWorkDir + "/runtime-tmp" );
        plexusProps.setProperty( "apps", nexusBaseDir + "/runtime/apps" );
        plexusProps.setProperty( "nexus-work", nexusWorkDir );
        plexusProps.setProperty( "nexus-app", nexusApp );
        plexusProps.setProperty( "webapp", nexusBaseDir + "/runtime/apps/nexus/webapp" );
        plexusProps.setProperty( "webapp-context-path", "/nexus" );
        plexusProps.setProperty( "application-conf", nexusWorkDir + "/conf" );
        plexusProps.setProperty( "log4j-prop-file", TestProperties.getPath( "default-configs" ) + "/log4j.properties" );
        plexusProps.setProperty( "jetty.xml", nexusBaseDir + "/conf/jetty.xml" );
        plexusProps.setProperty( "index.template.file", "templates/index-debug.vm" );
        plexusProps.setProperty( "security-xml-file", nexusWorkDir + "/conf/security.xml" );

        Set<String> sysProps = System.getProperties().stringPropertyNames();
        for ( String prop : sysProps )
        {
            if ( prop.startsWith( "plexus." ) )
            {
                String propName = prop.substring( 7 );
                if ( !plexusProps.containsKey( propName ) )
                {
                    plexusProps.setProperty( propName, System.getProperty( prop ) );
                }
            }
        }

        File containerProperties = new File( nexusWorkDir, "plexus.properties" );
        containerProperties.getParentFile().mkdirs();
        FileOutputStream out = new FileOutputStream( containerProperties );
        plexusProps.store( out, "Generated by NexusInstancesPool" );
        out.close();

        String forkedAppBooterHint = "TestForkedAppBooter" + nexusPort;

        ComponentDescriptor<ForkedAppBooter> baseComp;
        synchronized ( container )
        {
            baseComp =
                container.getComponentDescriptor( ForkedAppBooter.class, ForkedAppBooter.class.getName(),
                                                  "DefaultForkedAppBooter" );
        }

        PlexusConfiguration cfg = baseComp.getConfiguration();
        addChild( cfg, "disable-blocking", Boolean.TRUE.toString() );
        addChild( cfg, "debug", Boolean.FALSE.toString() );
        addChild( cfg, "java-cmd", "java" );
        addChild( cfg, "debug-port", TestProperties.getInteger( "debug-port", 5006 ).toString() );
        addChild( cfg, "debug-suspend", Boolean.TRUE.toString() );
        addChild(
                  cfg,
                  "debug-java-cmd",
                  "java -Xdebug -Xnoagent -Xrunjdwp:transport=dt_socket,server=y,suspend=@DEBUG_SUSPEND@,address=@DEBUG_PORT@ -Djava.compiler=NONE" );
        addChild( cfg, "launcher-class", "org.sonatype.appbooter.PlexusContainerHost" );
        addChild( cfg, "configuration", nexusBaseDir + "/conf/plexus.xml" );
        addChild( cfg, "basedir", nexusBaseDir );
        addChild( cfg, "temp-dir", TestProperties.getPath( "project.build.directory" ) + "/appbooter.tmp." + nexusPort );
        addChild( cfg, "classworldsJar", nexusBaseDir + "/lib/plexus-classworlds-1.4.jar" );
        addChild( cfg, "classworldsConf", nexusBaseDir + "/conf/classworlds.conf" );
        addChild( cfg, "class-path-elements", nexusApp + "/conf, " + nexusApp + "/lib/*.jar" );
        addChild( cfg, "sleep-after-start", "5000" );
        addChild( cfg, "control-port", controllerPort.toString() );
        addChild( cfg, "container-properties", containerProperties.getAbsolutePath() );

        ComponentDescriptor<StreamConsumer> consumer = new ComponentDescriptor<StreamConsumer>();
        consumer.setRoleClass( StreamConsumer.class );
        consumer.setRoleHint( "FileConsumer" + nexusPort );
        consumer.setImplementationClass( FileStreamConsumer.class );
        XmlPlexusConfiguration consumeCfg = new XmlPlexusConfiguration();
        consumeCfg.addChild( "destination", nexusWorkDir + "/nexus.log" );
        consumer.setConfiguration( consumeCfg );

        ComponentDescriptor<ForkedAppBooter> comp = new ComponentDescriptor<ForkedAppBooter>();
        BeanUtils.copyProperties( comp, baseComp );
        comp.setRoleClass( ForkedAppBooter.class );
        comp.setRoleHint( forkedAppBooterHint );
        comp.setImplementationClass( DefaultForkedAppBooter.class );

        ComponentRequirement requirement = new ComponentRequirement();
        requirement.setFieldName( "streamConsumer" );
        requirement.setRole( StreamConsumer.class.getName() );
        requirement.setRoleHint( "FileConsumer" + nexusPort );
        comp.addRequirement( requirement );

        ForkedAppBooter appBooter;
        synchronized ( container )
        {
            container.addComponentDescriptor( consumer );
            container.addComponentDescriptor( comp );
            appBooter = container.lookup( ForkedAppBooter.class, forkedAppBooterHint );
        }

        appBooter.start();
        NexusContext context = new NexusContext( appBooter, nexusPort, new File( nexusWorkDir ) );

        ForkedAppBooter forkedAppBooter = (ForkedAppBooter) context.getAppBooter();

        ControllerClient client = forkedAppBooter.getControllerClient();
        ping( client );

        StatusResource status = NexusStatusUtil.getNexusStatus( context.getPort() ).getData();
        if ( !status.getState().equals( "STARTED" ) )
        {
            throw new NexusIllegalStateException( "Failed to start nexus: " + status.getState() );
        }

        synchronized ( contexts )
        {
            contexts.add( context );
        }

        return context;
    }

    private void ping( ControllerClient client )
        throws NexusIllegalStateException
    {
        Integer cycles = TestProperties.getInteger( "startup-delay" );
        for ( int i = 0; i < cycles; i++ )
        {
            if ( client.ping() )
            {
                return;
            }
            sleep( 200 );
        }

        throw new NexusIllegalStateException( "Failed to start nexus after: " + cycles );
    }

    /*
     * (non-Javadoc)
     * @see org.sonatype.nexus.test.launcher.INexusInstancesFactory#shutdown()
     */
    public void shutdown()
        throws Exception
    {
        synchronized ( contexts )
        {
            while ( !contexts.isEmpty() )
            {
                NexusContext context = contexts.get( 0 );
                try
                {
                    destroyInstance( context );
                }
                catch ( Throwable t )
                {
                    t.printStackTrace();
                }
            }

            contexts = null;
        }

        synchronized ( container )
        {
            container = null;
        }
    }

    /*
     * (non-Javadoc)
     * @see
     * org.sonatype.nexus.test.launcher.INexusInstancesFactory#destroyInstance(org.sonatype.nexus.test.launcher.NexusContext
     * )
     */
    public void destroyInstance( NexusContext context )
        throws Exception
    {
        if ( context == null )
        {
            return;
        }

        ForkedAppBooter appBooter = (ForkedAppBooter) context.getAppBooter();
        appBooter.shutdown();

        synchronized ( container )
        {
            container.release( appBooter );
        }

        synchronized ( contexts )
        {
            contexts.remove( context );
        }

        context.release();
    }

}
